### ISSUE TITLE
[ogólne] - topka

### ISSUE THREAD

**Issue by kubaty007** [YaNkO0O/EndrjuBaton#3]

**Comment by kubaty007** [comment]
### Poprawki:

- [x] - brakuje licznika produktów w koszyku
- [x] - bordery powinny być na całą szerokość strony
![Image](https://user-images.githubusercontent.com/62720503/201927352-5e4b189e-b2dd-41df-be60-bdf81aba684f.png)

- [x] - poprawiłbym RWD bo na tej szerokości jest już trochę ciasno
![Image](https://user-images.githubusercontent.com/62720503/201927649-efc5b186-5a3b-475f-aaa4-7d56af1a1270.png)

- [x] - dostosowanie do projektu graficznego (głównie koszyk ale cała wymaga pracy)
![Image](https://user-images.githubusercontent.com/62720503/201927871-002d7401-4af3-4a59-b383-14ec2af694d3.png)

- [x] - hamburger menu powinno być wewnątrz `<header>`, podobnie mobileNav
![Image](https://user-images.githubusercontent.com/62720503/202454981-5646bfa3-4f8b-4253-9d99-9ec2f1f6f6b0.png)

- [x] - jedynym tagiem, który może bezpośrednio znajdować się w `<ul>` jest `<li>`
![Image](https://user-images.githubusercontent.com/62720503/202455302-6b48eb39-4938-411d-8659-9298233d0634.png)

**Comment by YaNkO0O** [comment]
jak mam w takim razie stworzyc linki do tego menu?

**Comment by kubaty007** [comment]
@YaNkO0O 
> jak mam w takim razie stworzyc linki do tego menu?
```
<ul>
    <li>
        <a></a>
    </li>
    <li>
        <a></a>
    </li>
    <li>
        <a></a>
    </li>
</ul>
```

**Comment by kubaty007** [comment]
### Poprawki:

- [x] - dopasowanie do projektu graficznego:
![Image](https://user-images.githubusercontent.com/62720503/203015423-9bd3936d-a00a-4a99-8a70-34a100e71318.png)

- [x] - u was jest `konto` zamiast `moje konto`

- [ ] - mobilne menu nie jest na całej szerokości 
![Image](https://user-images.githubusercontent.com/62720503/203016369-debef774-f5fb-4959-86e6-2a5519d1c2af.png)

- [x] - `<div>` nie powinien znajdować się wewnątrz elementu `<i>`
![Image](https://user-images.githubusercontent.com/62720503/203016989-69235a2b-d415-4c10-8563-082dc37d7dd4.png)

- [ ] - w `<nav>` możecie użyć listy (`<li>`)
![Image](https://user-images.githubusercontent.com/62720503/203017270-8cd005a0-6b9a-4868-8a97-79019fe9de5f.png)

- [x] -  jedynym elementem który powinien się znajdować bezpośrednio w  `<ul>` jest `<li>` 
![Image](https://user-images.githubusercontent.com/62720503/203017707-1f73abbf-4421-4d20-8b21-38e75203486d.png)

 **fajnie, że macie dobrze ogarnięte nazewnictwo klas 🥇**
