### ISSUE TITLE
[ogólne] - uwagi ogólne

### ISSUE THREAD

**Issue by kubaty007** [YaNkO0O/EndrjuBaton#9]

**Comment by kubaty007** [comment]
### Poprawki:

- [x] - nie wiem co tu się zadziało, wygląda jak nieudany resolve konfliktów. W każdym razie `main.scss` do poprawy. Dodatkowo zduplikowane `background-color`

![Image](https://user-images.githubusercontent.com/62720503/201926403-8b5c0ea2-9dc2-473a-81c3-8283cea96fa3.png)

![Image](https://user-images.githubusercontent.com/62720503/201926450-c73a7836-1ee8-4296-84ca-f8adb3a58b55.png)

**Comment by YaNkO0O** [comment]
ja tego nie mam u siebie

**Comment by kubaty007** [comment]
a zpullowałeś?
